[advisories]
ignore = [
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = [
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[sources.allow-org]
#github = ["M4SS-Code"]
